- name: setup catalogue server
  hosts: catalogue
  connection: local
  become: yes
  tasks:
  - name: disbale nodejs module
    ansible.builtin.command:
      cmd: "dnf module disable nodejs -y"
  - name: enable nodejs module
    ansible.builtin.command:
      cmd: "dnf module enable nodejs:20 -y"

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      comment: "roboshop system user"
      system: yes
  - name: create app directory
    ansible.builtin.file: 
      path: /app
      state: directory

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
      

  - name: unzip the catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install node dependencies
    community.general.npm:
      path: /app

  - name: update the catalogue systemd service file
    ansible.builtin.template:
      src: catalogue.server
      dest: /etc/systemd/system/catalogue.service
  - name: create mongodb repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client 
    ansible.builtin.package:
      name: mongodb-mongosh 
      state: present
  - name: replace the bindIp in the mongodb config file
    ansible.builtin.replace:
      path: /etc/mongod.conf  
      regexp: "127.0.0.1"
      replace: "0.0.0.0"

  - name: Load schema into MongoDB
    ansible.builtin.shell: 
      cmd: "mongosh --host mongodb.reddy3.fun </app/schema/catalogue.js"
    register: catalogue_output




  - name: get Db data creation status
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"


 