[local]
local

[mongodb]
mongodb.reddy3.fun

[redis]
redis.reddy3.fun

[mysql]
mysql.reddy3.fun

[rabbitmq]
rabbitmq.reddy3.fun

[catalogue]
catalogue.reddy3.fun

[cart]
cart.reddy3.fun

[user]
user.reddy3.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

