- name: setup rabbitmq
  hosts: rabbitmq
  become: true
  tasks:
  - name: install rabbitmq
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name : start and enable the rabbitmq service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: true

  - name: create and change permissions for rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: "roboshop123"
        - vhost: /
          configure_priv: .*
          write_priv: .*
          read_priv: .*
      state: present
      